### ISSUE TITLE
First received frame was not SETTINGS. Hex dump for first 5 bytes

### ISSUE THREAD

**Issue by smoooochy** [grpc/grpc-java#3421]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0

### What JVM are you using (`java -version`)?
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### What did you do?
Inside a test I ran a grpc server and 5 clients that accessed the server concurrently (all from the same IP; everyone with its own channel). This is only happening sometimes, looks to me like some kind of race condition within grpc.

Gradle dependencies:
```
 compile 'com.google.protobuf:protobuf-java:3.0.0'
    compile 'io.grpc:grpc-netty:1.4.0'
    compile 'io.grpc:grpc-stub:1.4.0'
    compile 'io.grpc:grpc-protobuf:1.4.0'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.8.2'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.8.2'
    testCompile 'org.testng:testng:6.8'
```

### What did you expect to see?
Successful call

### What did you see instead?
```
io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at xyz.CalculationServiceGrpc$CalculationServiceBlockingStub.getResult(CalculationServiceGrpc.java:261)
	at xyz.Calculation.run(Calculation.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000000401
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:320)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:221)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
```

**Comment by smoooochy** [comment]
Sometimes I additionally get:
```
io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
Received Goaway
HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000000040100000000
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	....
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by carl-mastrangelo** [comment]
Can you show how you are constructing your channel?  It sounds like use are calling `usePlaintext(false)`

**Comment by smoooochy** [comment]
```
channel = NettyChannelBuilder.forAddress(ip, UrlDownloaderServer.DEFAULT_SERVER_PORT)
                .keepAliveTime(60, TimeUnit.SECONDS)
                .keepAliveWithoutCalls(true)
                .usePlaintext(true).build();
```

**Comment by carl-mastrangelo** [comment]
Thats very strange.  It seems the client is setting the ACK bit when it should not be.  Can you turn on client side frame logging?

Here is the log config to turn it on: 

https://gist.github.com/carl-mastrangelo/49f6d6a8ff29200fcb7d9e25e473b2d0

**Comment by smoooochy** [comment]
[compressionError.txt](https://github.com/grpc/grpc-java/files/1263365/compressionError.txt)
Ok, now this time a new error

```

Timestamp: 1504092341854

io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: COMPRESSION_ERROR
Received Goaway
HPACK - illegal index value
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)


```

I attached the log file (couldn't capture it on console, was just to much, timestamp should help find it (also should be near the end, since I did exit the jvm directly after that exception)

**Comment by smoooochy** [comment]
And here is the log file for the original error:

[notSettings.txt](https://github.com/grpc/grpc-java/files/1263454/notSettings.txt)


```
Timestamp: 1504094178219
io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	...
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000080700
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:320)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:221)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more

```

**Comment by smoooochy** [comment]
Another (and different?) one:

```
Timestamp: 1504146049671
io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
Received Goaway
HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000000040100000000000074012400000003000000000f41
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)

```
[goAway.txt](https://github.com/grpc/grpc-java/files/1265582/goAway.txt)

**Comment by carl-mastrangelo** [comment]
@smoooochy thank you that is very helpful.  From my reading:

1.  Client 0x42d068b4 Sends Settings
2.  Client sends Window Update
3.  Server 0x8d72ea22 Sends Settings
4.  Server sends Window UPDATE
5.  Client Receives settings
6.  Client Sends Settings ack
7.  Client Sends Window update
8.  Client Sends HEADERS
9.  Client Sends DATA
10. Server Sends Goaway, invalid Settings (for step 6.)

So it looks like some how the Client is sending the ack too early, and it is perhaps leap frogging the connection preface.  There was a bug fix in Netty a few weeks ago that changed how settings frames were handled.   Could you try gRPC 1.5.0 to see if the problem persists?

**Comment by smoooochy** [comment]
Still happens,
log file: 
[with150.txt](https://github.com/grpc/grpc-java/files/1265878/with150.txt)

```
Timestamp: 1504155763885
io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000000401
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:320)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:221)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
```

**Comment by smoooochy** [comment]
And a different one:

[with150_2.txt](https://github.com/grpc/grpc-java/files/1265901/with150_2.txt)

```
Timestamp: 1504156261806
io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
Received Goaway
HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000000040100000000000074012400000003000000000f41
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
```

**Comment by ejona86** [comment]
@carl-mastrangelo, we should check and see what version that SETTINGS bug was fixed in Netty, and then see what version of gRPC would have included that Netty version.

**Comment by carl-mastrangelo** [comment]
@smoooochy 1.6 was released since you filed the bug, which also included several netty bugs.  Can you check if its still happening?

**Comment by smoooochy** [comment]
Took me some time for this to check, apologies.
The problem is still happening with version 1.6.

**Comment by carl-mastrangelo** [comment]
I'm pretty stumped.    A reproducing test case would be ideal; without one that I can run, I'm not sure how to move forward.

**Comment by smoooochy** [comment]
Ok, will take me some time to strip it down to the bare minimum (probably 1-2 weeks until I find time but I will try)

**Comment by ejona86** [comment]
Closing due to inactivity. @smoooochy, if you have more information you can post it here and we can reopen the issue.
