### ISSUE TITLE
Getting error while GRPC call: Can't find decompressor for deflate

### ISSUE THREAD

**Issue by sridharprasath** [grpc/grpc-java#7095]
I have an application where I have to send a number and get a corresponding image from the server. The server is C++ and it uses Gzip compression and deflate algorithms to send the compressed data to the client. 

On the android side, I have to call the API and the response will be stored in 'image'. 
The request is 'CID'. The service is 'getsampleimage'. The response is 'image'.

//GRPC call
Image image = blockingStub.withCompression("gzip").getSampleImage(CID);

But if I use the above method, it is throwing the error 'cant find decompressor for deflate'. I dont know whether it is correctly decompressing the Gzip format or not. Does anybody know how to do decompression on the android client side for the image data(Byte array)

**Comment by voidzcy** [comment]
grpc-java does not support deflate. Currently we only support gzip format.

**Comment by sridharprasath** [comment]
@voidzcy Thank you for your reply. My teammate is building the c++ server. He has used  '  builder.SetDefaultCompressionAlgorithm(GRPC_COMPRESS_GZIP)' while building the GRPC channel... and he has used '  builder.SetDefaultCompressionAlgorithm(GRPC_COMPRESS_GZIP)' while calling the RPC service..

If he has used this, how can I get the response without getting that above error.. Could you please tell me what changes I have to make in the server(C++ side) or client(Android side)

**Comment by voidzcy** [comment]
In C++, `builder.SetDefaultCompressionAlgorithm(GRPC_COMPRESS_GZIP)` sets the default compression algorithm to gzip on the Channel level. That is, messages sent on this channel are compressed with gzip. `context->set_compression_algorithm(GRPC_COMPRESS_DEFLATE)` applies to each RPC calls, it _overwrites_ the compression algorithm to be DEFLATE. (For more information please see [C++'s compression example](https://github.com/grpc/grpc/tree/master/examples/cpp/compression)).

Since grpc-java only supports gzip, you may not want to overwrite each call's compression with DEFLATE.

**Comment by sridharprasath** [comment]
@voidzcy  Thanks for the information. So, if I remove **context>set_compression_algorithm(GRPC_COMPRESS_DEFLATE)**  on the server side and Image image = blockingStub.**withCompression("gzip")**.getSampleImage(CID) on the client side will able to decompress the response?
My doubt is because the server is instantiating compression algorithm on the **Channel** level and the client is instantiating decompression algorithm on the **RPC call** level.. Hope to hear from you.
Thank you in advance.

**Comment by ejona86** [comment]
[`set_compression_level()`](https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context.html#aa029ac26886b5f2c2171fc94a6be43d2) would be much better than set_compression_algorithm, as it lets the server choose an appropriate algorithm.

The C++ gRPC server seems like it has a bug, as it should have used no compression in that case. I've filed issue https://github.com/grpc/grpc/issues/23191 .

**Comment by voidzcy** [comment]
@sridharprasath This is how compression works between client and server:

On the client side, `AbstractStub.withCompression()` sets the compression format to be used for the message sent to server. Internally, gRPC also sends the server _a list of encoding formats_ that it is able to decompress. On the server side, the server will only compress response messages using the algorithm you set when the compression algorithm appears in the list of encodings that client advertised to accept. Otherwise, the server will just not encode response messages.

**Comment by ejona86** [comment]
Seems like this is resolved from the Java side. C still has their issue. I would suggest using GZIP or set_compression_level. Closing. But if we've missed something, comment and it can be reopened.

**Comment by sridharprasath** [comment]
@ejona86 @voidzcy we still have this problem... the c++ server removed the deflate algorithm and just keeping the **builder.SetDefaultCompressionAlgorithm(GRPC_COMPRESS_GZIP)**  .... the java client  compresses the data with **AbstractStub.withCompression("gzip)**  method.. Still its throwing some errors..


@ejona86 you have told to use setcompressionlevel() instead of setcompressionalgorithm() ..Is there any example if doing that? Or is there any other way  to send compressed data from java client to c++ server..?Thank you in advance.

**Comment by ejona86** [comment]
@sridharprasath, please post the errors you are seeing.

I don't understand the problem with compression level. Instead of calling `SetDefaultCompressionAlgorithm()` call [`SetDefaultCompressionLevel`](https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_builder.html#af9aee4466612c84038d20c9371135061). The lower levels are less compressed but use less CPU.
