### ISSUE TITLE
message of client can't send to server.

### ISSUE THREAD

**Issue by louiewh** [grpc/grpc-java#7795]
### What version of gRPC-Java are you using?
    implementation 'io.grpc:grpc-okhttp:1.29.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.29.0'
    implementation 'io.grpc:grpc-stub:1.29.0'

### What is your environment?
android

### What did you expect to see?
1. Grpc as a client at android,   client will send  message to service,  but some message  loss

### What did you see instead?
I have debug the code,  I find that  message will cached before DNS resolve,  for example client cached two message, when DNS resloved, only one message to send.

### Steps to reproduce the bug
Client send two message before DNS reslove,   this issue happen 1/10. The messages using different ManagedChannel. one channel is http , another is https, the two channel have same host

**Comment by louiewh** [comment]
[
[log2.log](https://github.com/grpc/grpc-java/files/5794402/log2.log)
](url)

this is the log .
At first client send a message name handshake using https with port 8081.  then client send a message named GetSingerSong. when dns resloved only GetSingerSong message send .

**Comment by ejona86** [comment]
Since the two channels are to different ports, there may be network issues that only impact one port. For example, maybe a firewall rule prevents contacting 8081 and it will take longer for the Channel to timeout its connection attempt.

It seems you added quite a bit of logging to grpc. I dug through a bit and didn't see too much jump out at me. The `UpdateBalancingState` calls and `PickResults` are important, but it is a bit harder to follow without having an ID for each channel. I think the TLS channel is still connecting.

I think the easiest thing to do is "wait longer" for the RPC to fail. It may take 20+ seconds for a connection attempt to time out/fail. Getting a clear error message helps debugging immensely.

The logs for [`transportRead()`](https://github.com/grpc/grpc-java/blob/b66d182bb9aafe8d88ac56c282d09b0b8be4ced7/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L545) and [`transportShutdown()`](https://github.com/grpc/grpc-java/blob/b66d182bb9aafe8d88ac56c282d09b0b8be4ced7/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L571) tell us the state of individual connection attempts. If all connection attempts for a channel fail then the RPC will fail. I see `144488:D/GRPC    (31499): READY` in the log, which would be for one channel, but I don't see a second log entry for the second channel. Similarly, I don't see a second set of `UpdateBalancingState` calls and `PickResults` that are obviously for the second channel.

**Comment by louiewh** [comment]
I have find two fix

 https://github.com/grpc/grpc-java/commit/50d8be70b05af6fae1d9556bdf26e4292db2de20
 https://github.com/grpc/grpc-java/commit/f36f0e90462dcb86279b232fb4c3cbca8f6bd873

There isn't  too way to debug. 
so I update grpc version to lastest.
Thank you

**Comment by ejona86** [comment]
@louiewh, have you tried a newer gRPC version and it works (so we can close this issue)? Or are you trying a new gRPC version to see if it helps the situation (so we should wait for the results)?

**Comment by louiewh** [comment]
@ejona86 .  I have update grpc version .  It seem  work good .

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by louiewh** [comment]
@ejona86
this issue still exit at version 1.34.1
this is my app log. 

03-01 15:30:34.837 12007 12007 D KtvPlayRequestChain: execute com.tme.ktv.sdk.player.GetSongInfoInterceptor@8f92f4e start
03-01 15:30:34.838 12007 12007 D KtvSdk  : KtvPlayer:[at .print(LogTrace.java:108)  onExecuteStart com.tme.ktv.sdk.player.GetSongInfoInterceptor@8f92f4e
03-01 15:30:34.838 12007 12007 D KtvSdk  : KtvPlayer:onExecuteStart com.tme.ktv.sdk.player.GetSongInfoInterceptor@8f92f4e
03-01 15:30:34.850 12007 12007 D KtvSdk  : GrpcCall: -> ktv.engine.grpc.protocol.SdkMedia$GetSongInfoReq# GrpcCall.enqueue request
03-01 15:30:34.992 12007 13801 D KtvSdk  : GrpcCall: -> ktv.engine.grpc.protocol.SdkMedia$GetSongInfoRsp# GrpcCall.onSuccess response 
03-01 15:30:34.993 12007 12007 D KtvPlayRequestChain: execute com.tme.ktv.sdk.player.GetSongInfoInterceptor@8f92f4e finish
03-01 15:30:34.993 12007 12007 D KtvSdk  : KtvPlayer:[at .print(LogTrace.java:108)  onExecuteEnd com.tme.ktv.sdk.player.GetSongInfoInterceptor@8f92f4e
03-01 15:34:21.740 12007 12007 D KtvPlayRequestChain: execute com.tme.ktv.sdk.player.GetSongInfoInterceptor@ba9f16a start
03-01 15:34:21.740 12007 12007 D KtvSdk  : KtvPlayer:[at .print(LogTrace.java:108)  onExecuteStart com.tme.ktv.sdk.player.GetSongInfoInterceptor@ba9f16a
03-01 15:34:21.740 12007 12007 D KtvSdk  : KtvPlayer:onExecuteStart com.tme.ktv.sdk.player.GetSongInfoInterceptor@ba9f16a
03-01 15:34:21.750 12007 12007 D KtvSdk  : GrpcCall: -> ktv.engine.grpc.protocol.SdkMedia$GetSongInfoReq# GrpcCall.enqueue request
03-01 15:39:00.141 12007 12007 D KtvSdk  : KtvPlayRequestChain:[at .print(LogTrace.java:108)  pause preInterceptor = com.tme.ktv.sdk.player.GetSongInfoInterceptor@ba9f16a
03-01 15:39:47.910 12007 12007 D KtvPlayRequestChain: execute com.tme.ktv.sdk.player.GetSongInfoInterceptor@b5d626c start

**Comment by ejona86** [comment]
@louiewh, that log doesn't tell me much, other than after 5 minutes the RPC hadn't completed. Five minutes is quite a long time. I'd expect gRPC to give an error in less than 5 minutes if it has trouble connecting to the server. That makes it seem most likely that 1) the server is hung and not yet responded or 2) connectivity to the server has been lost. gRPC can't do much for (1), but for (2) you can use a combination of [`channelBuilder.idleTimeout(45, TimeUnit.SECONDS)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#idleTimeout-long-java.util.concurrent.TimeUnit-) to close a TCP connection before certain networks might silently kill it and [`channelBuilder.keepAliveTime(5, TimeUnit.MINUTES)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit-) to have gRPC actively check the health of the TCP connection (numbers provided are just samples).

Given there were 4 minutes between the two RPCs, we'd primarily be relying on idleTime(). But given flaky networks, having a back-up checker via keepAliveTime is a good idea. Note that keepalives less than 5 minutes are rejected by gRPC servers by default.

**Comment by ejona86** [comment]
It seems likely my previous suggestion resolves the problem for you. Please report back if it doesn't and this can be reopened (like before).
